templates_dir: 'templates'
root_dir: ''
data_dir: 'data'
lyrics_ext: '.md'
output_dir: 'output'
temp_dir: 'tmp'
    
song_meta:
  - songname
  - songname_eng
  - transcriber
  - linewidth
  - textby
  - musicby
