templates_dir: 'templates'
root_dir: ''
data_dir: 'data'
lyrics_ext: '.md'
output_dir: 'output'
temp_dir: 'tmp'

book:
    chapters: 
    - סאָציאַליסטישע און אַנטיפֿאַשיסטישע לידער # 0
    - ליבעלידער # 1
    - לידער װעגן ייִדיש און ייִדישקײַט #2
    - לידער װעגן משפּחה און לעבן #3
    - לידער װעגן נױט און אָרעמקײַט #4
    - אימיגראַנטישע לידער #5
    - װיגלידער #6
    - קינדערלידער #7
    - קאָמישע לידער #8
    name:    ייִדישע פֿאָלקסלידער
    filename: yidishe-folkslider
    
song_meta:
  - songname
  - songname_eng
  - transcriber
  - linewidth
  - textby
  - musicby
